apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: s3-workload

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

# Optional: Use job instead of deployment
# - job.yaml

commonLabels:
  app: s3-workload
  managed-by: kustomize

