apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
  namespace: s3-workload
  labels:
    app: s3-workload
type: Opaque
stringData:
  # Replace these with your actual credentials
  accessKey: "YOUR_ACCESS_KEY"
  secretKey: "YOUR_SECRET_KEY"

