apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: s3-workload
  namespace: s3-workload
  labels:
    app: s3-workload
spec:
  selector:
    matchLabels:
      app: s3-workload
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s

