apiVersion: v1
kind: Service
metadata:
  name: s3-workload-metrics
  namespace: s3-workload
  labels:
    app: s3-workload
spec:
  type: ClusterIP
  selector:
    app: s3-workload
  ports:
  - name: http
    port: 9090
    targetPort: metrics
    protocol: TCP

